#!/bin/sh

# adjust these
OUTPUT_DIR="/var/www/jache.re/"
BIBTEX_FILE="./files/jachere.bib"
TEMPLATE_FILE="./files/template/main.html"

# No editing beyond this comment
INPUT_DIR="$(pwd)/"

git diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD | grep -E '.md' | while read file ; do

	# prepare input file string
	INPUT_FILE="${file#\"}"

	# prepare relative output file path w/o extension
	OUTPUT_RELATIVE=${INPUT_FILE%.*}

	# render the file
	. ./pancake.sh/render
done

# sync files and prepare images for hosting
. ./pancake.sh/post-render
