#!/bin/sh
# sync files to output dir
if [ "$UPDATE" = true ] ; then
    # TODO enable subfolders
    mkdir "${OUTPUT_DIR}files"
    git -C "$INPUT_DIR" diff-tree -r --name-only --no-commit-id HEAD@{1} HEAD | grep 'files' | while read file ; do
		cp "${INPUT_DIR}${file}" "${OUTPUT_DIR}${file}"
	done
else
    rsync -avu "${INPUT_DIR}files/" "${OUTPUT_DIR}files"
fi

# resizes and dithers copied images
find "$OUTPUT_DIR" -type f \( -name \*.png \) -exec mogrify -resize 640x -dither FloydSteinberg -colors 32 -format png -auto-orient {} \;
find "$OUTPUT_DIR" -type f \( -name \*.jpg -o -name \*.jpeg \) -exec mogrify -resize 640x -dither FloydSteinberg -colors 32 -format png -auto-orient {} \; -exec rm {} \;